import {Myra} from './myra';
export var MYRAS: Myra[] = [
  { 'id': 0, 
    'name': 'Myra the Ferryboat' },
  { 'id': 2, 
    'name': 'The ferry from Palm Beach to Coasters Retreat and the Basin is called Myra.',
    'src1': '5-myra4-5-is-myra-b-sky-only.png',
    'src2': '5-myra4-5-is-myra-b-myra-only.png',
    'src3': '5-myra4-5-is-myra-b-wharf-only.png'
  },
  { 'id': 13, 'name': 'Bombasto' },
  { 'id': 14, 'name': 'Celeritas' },
  { 'id': 15, 'name': 'Magneta' },
  { 'id': 16, 'name': 'RubberMan' },
  { 'id': 17, 
    'name': 'Dynama',
    'power': 'Really Smart',  },
  { 'id': 18, 
    'name': 'Dr IQ', 
    'power': 'Really Smart', 
    'alterEgo': 'Chuck Overstreet'},
  { 'id': 19, 
    'name': 'Magma' },
  { 'id': 20, 
    'name': 'Tornado' },
  { 'id': 42, 
    'name': 'SkyDog', 
    'power': 'Fetch any object at any distance', 
    'alterEgo': 'Leslie Rollover'},
  { 'id': 8, 
    'name': 'J-Dragon', 
    'power': 'Gets very annoyed', 
    'alterEgo': 'Park Jinyoung'}
];
